vich_uploader:
    db_driver: orm
    mappings:
        files:
            uri_prefix: ~
            upload_destination: custom_uploads_fs
            namer: vich_uploader.namer_uniqid
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true

parameters:
    images_directory: '%kernel.project_dir%/public/images'

